### ISSUE TITLE
Populate the contents of a hub with the contents of another hub

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/populator#107]
## Description
As a community manager I want to be easily able to move Hubs from one enviornment to another 

## Acceptance criteria

- [ ] Create / update all challenges in the target hub with the challenges in the source hub
- [ ] Create new organizations?
- [ ] Create new user profiles?

Notes: 
- target hub should already be created
- will need to specify two sets of credentials. Impact on client-lib?

## Additional Context
This is in particular to make it possible to move content from Hubs on Demo to be on Prod e.g. ifs2025
